# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources/FilterToolDesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1062, 875)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.templates_tab = QtWidgets.QWidget()
        self.templates_tab.setObjectName("templates_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.templates_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.templates_tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.stopBand1DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.stopBand1DoubleSpinBox.setMaximum(99999999999.0)
        self.stopBand1DoubleSpinBox.setSingleStep(0.01)
        self.stopBand1DoubleSpinBox.setObjectName("stopBand1DoubleSpinBox")
        self.horizontalLayout_6.addWidget(self.stopBand1DoubleSpinBox)
        self.gridLayout_11.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.stopBand2_horizontalLayout = QtWidgets.QHBoxLayout()
        self.stopBand2_horizontalLayout.setObjectName("stopBand2_horizontalLayout")
        self.stopBand2_label = QtWidgets.QLabel(self.groupBox)
        self.stopBand2_label.setObjectName("stopBand2_label")
        self.stopBand2_horizontalLayout.addWidget(self.stopBand2_label)
        self.stopBand2DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.stopBand2DoubleSpinBox.setMaximum(99999999999.0)
        self.stopBand2DoubleSpinBox.setSingleStep(0.01)
        self.stopBand2DoubleSpinBox.setObjectName("stopBand2DoubleSpinBox")
        self.stopBand2_horizontalLayout.addWidget(self.stopBand2DoubleSpinBox)
        self.gridLayout_11.addLayout(self.stopBand2_horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.passBand1DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.passBand1DoubleSpinBox.setMaximum(99999999999.0)
        self.passBand1DoubleSpinBox.setSingleStep(0.01)
        self.passBand1DoubleSpinBox.setObjectName("passBand1DoubleSpinBox")
        self.horizontalLayout_3.addWidget(self.passBand1DoubleSpinBox)
        self.gridLayout_11.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.passBand2_horizontalLayout = QtWidgets.QHBoxLayout()
        self.passBand2_horizontalLayout.setObjectName("passBand2_horizontalLayout")
        self.passBand2_label = QtWidgets.QLabel(self.groupBox)
        self.passBand2_label.setObjectName("passBand2_label")
        self.passBand2_horizontalLayout.addWidget(self.passBand2_label)
        self.passBand2DoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.passBand2DoubleSpinBox.setMaximum(99999999999.0)
        self.passBand2DoubleSpinBox.setSingleStep(0.01)
        self.passBand2DoubleSpinBox.setObjectName("passBand2DoubleSpinBox")
        self.passBand2_horizontalLayout.addWidget(self.passBand2DoubleSpinBox)
        self.gridLayout_11.addLayout(self.passBand2_horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.minAttnDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.minAttnDoubleSpinBox.setObjectName("minAttnDoubleSpinBox")
        self.horizontalLayout_2.addWidget(self.minAttnDoubleSpinBox)
        self.gridLayout_11.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.maxAttnDoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.maxAttnDoubleSpinBox.setObjectName("maxAttnDoubleSpinBox")
        self.horizontalLayout_4.addWidget(self.maxAttnDoubleSpinBox)
        self.gridLayout_11.addLayout(self.horizontalLayout_4, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_11, 1, 1, 1, 1)
        self.setTemplateButton = QtWidgets.QPushButton(self.groupBox)
        self.setTemplateButton.setObjectName("setTemplateButton")
        self.gridLayout_7.addWidget(self.setTemplateButton, 2, 1, 1, 1)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.filterTypeComboBox = QtWidgets.QComboBox(self.groupBox)
        self.filterTypeComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.filterTypeComboBox.setObjectName("filterTypeComboBox")
        self.filterTypeComboBox.addItem("")
        self.filterTypeComboBox.addItem("")
        self.filterTypeComboBox.addItem("")
        self.filterTypeComboBox.addItem("")
        self.filterTypeComboBox.addItem("")
        self.horizontalLayout_14.addWidget(self.filterTypeComboBox)
        self.gridLayout_7.addLayout(self.horizontalLayout_14, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.templates_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.maxQRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.maxQRadioButton.setObjectName("maxQRadioButton")
        self.horizontalLayout_15.addWidget(self.maxQRadioButton)
        self.maxQdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.maxQdoubleSpinBox.setObjectName("maxQdoubleSpinBox")
        self.horizontalLayout_15.addWidget(self.maxQdoubleSpinBox)
        self.gridLayout_8.addLayout(self.horizontalLayout_15, 1, 0, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.minMaxRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.minMaxRadioButton.setObjectName("minMaxRadioButton")
        self.horizontalLayout_17.addWidget(self.minMaxRadioButton)
        self.minOrderSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.minOrderSpinBox.setObjectName("minOrderSpinBox")
        self.horizontalLayout_17.addWidget(self.minOrderSpinBox)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.maxOrderSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.maxOrderSpinBox.setObjectName("maxOrderSpinBox")
        self.horizontalLayout_17.addWidget(self.maxOrderSpinBox)
        self.gridLayout_8.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.customOrderRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.customOrderRadioButton.setObjectName("customOrderRadioButton")
        self.horizontalLayout_18.addWidget(self.customOrderRadioButton)
        self.customOrderSpinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.customOrderSpinBox.setObjectName("customOrderSpinBox")
        self.horizontalLayout_18.addWidget(self.customOrderSpinBox)
        self.gridLayout_8.addLayout(self.horizontalLayout_18, 2, 0, 1, 1)
        self.previewApproxButton = QtWidgets.QPushButton(self.groupBox_3)
        self.previewApproxButton.setObjectName("previewApproxButton")
        self.gridLayout_8.addWidget(self.previewApproxButton, 3, 0, 1, 1)
        self.clearApproxButton = QtWidgets.QPushButton(self.groupBox_3)
        self.clearApproxButton.setObjectName("clearApproxButton")
        self.gridLayout_8.addWidget(self.clearApproxButton, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.approximationComboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.approximationComboBox.setObjectName("approximationComboBox")
        self.approximationComboBox.addItem("")
        self.approximationComboBox.addItem("")
        self.approximationComboBox.addItem("")
        self.approximationComboBox.addItem("")
        self.approximationComboBox.addItem("")
        self.approximationComboBox.addItem("")
        self.approximationComboBox.addItem("")
        self.horizontalLayout_16.addWidget(self.approximationComboBox)
        self.gridLayout.addLayout(self.horizontalLayout_16, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.templates_tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.saveResultsPushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.saveResultsPushButton.setObjectName("saveResultsPushButton")
        self.gridLayout_10.addWidget(self.saveResultsPushButton, 2, 0, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.attenuationCurvesCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.attenuationCurvesCheckBox.setObjectName("attenuationCurvesCheckBox")
        self.gridLayout_9.addWidget(self.attenuationCurvesCheckBox, 0, 0, 1, 1)
        self.stepResponseCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.stepResponseCheckBox.setObjectName("stepResponseCheckBox")
        self.gridLayout_9.addWidget(self.stepResponseCheckBox, 0, 1, 1, 1)
        self.phaseCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.phaseCheckBox.setObjectName("phaseCheckBox")
        self.gridLayout_9.addWidget(self.phaseCheckBox, 1, 0, 1, 1)
        self.sPlaneCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.sPlaneCheckBox.setObjectName("sPlaneCheckBox")
        self.gridLayout_9.addWidget(self.sPlaneCheckBox, 1, 1, 1, 1)
        self.groupDelayCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.groupDelayCheckBox.setObjectName("groupDelayCheckBox")
        self.gridLayout_9.addWidget(self.groupDelayCheckBox, 2, 0, 1, 1)
        self.freqResponseCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.freqResponseCheckBox.setObjectName("freqResponseCheckBox")
        self.gridLayout_9.addWidget(self.freqResponseCheckBox, 2, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.computePushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.computePushButton.setObjectName("computePushButton")
        self.gridLayout_10.addWidget(self.computePushButton, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.plotsLayout = QtWidgets.QVBoxLayout()
        self.plotsLayout.setObjectName("plotsLayout")
        self.gridLayout_2.addLayout(self.plotsLayout, 0, 1, 1, 1)
        self.tabWidget.addTab(self.templates_tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.current_approx_comboBox = QtWidgets.QComboBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_approx_comboBox.sizePolicy().hasHeightForWidth())
        self.current_approx_comboBox.setSizePolicy(sizePolicy)
        self.current_approx_comboBox.setObjectName("current_approx_comboBox")
        self.current_approx_comboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.current_approx_comboBox)
        self.gridLayout_16.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.zeros_listWidget = QtWidgets.QListWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zeros_listWidget.sizePolicy().hasHeightForWidth())
        self.zeros_listWidget.setSizePolicy(sizePolicy)
        self.zeros_listWidget.setObjectName("zeros_listWidget")
        self.gridLayout_12.addWidget(self.zeros_listWidget, 0, 1, 1, 1)
        self.add_zeroButton = QtWidgets.QPushButton(self.groupBox_5)
        self.add_zeroButton.setObjectName("add_zeroButton")
        self.gridLayout_12.addWidget(self.add_zeroButton, 1, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_5, 1, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.poles_listWidget = QtWidgets.QListWidget(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.poles_listWidget.sizePolicy().hasHeightForWidth())
        self.poles_listWidget.setSizePolicy(sizePolicy)
        self.poles_listWidget.setObjectName("poles_listWidget")
        self.gridLayout_13.addWidget(self.poles_listWidget, 0, 1, 1, 1)
        self.add_poleButton = QtWidgets.QPushButton(self.groupBox_6)
        self.add_poleButton.setObjectName("add_poleButton")
        self.gridLayout_13.addWidget(self.add_poleButton, 1, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.current_stage_comboBox = QtWidgets.QComboBox(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.current_stage_comboBox.sizePolicy().hasHeightForWidth())
        self.current_stage_comboBox.setSizePolicy(sizePolicy)
        self.current_stage_comboBox.setObjectName("current_stage_comboBox")
        self.horizontalLayout_8.addWidget(self.current_stage_comboBox)
        self.gridLayout_17.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.stage_zerosList = QtWidgets.QListWidget(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage_zerosList.sizePolicy().hasHeightForWidth())
        self.stage_zerosList.setSizePolicy(sizePolicy)
        self.stage_zerosList.setObjectName("stage_zerosList")
        self.gridLayout_20.addWidget(self.stage_zerosList, 0, 0, 1, 1)
        self.remove_zeroButton = QtWidgets.QPushButton(self.groupBox_10)
        self.remove_zeroButton.setObjectName("remove_zeroButton")
        self.gridLayout_20.addWidget(self.remove_zeroButton, 1, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_10, 0, 3, 5, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_8)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.stage_polesList = QtWidgets.QListWidget(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stage_polesList.sizePolicy().hasHeightForWidth())
        self.stage_polesList.setSizePolicy(sizePolicy)
        self.stage_polesList.setObjectName("stage_polesList")
        self.gridLayout_19.addWidget(self.stage_polesList, 0, 0, 1, 1)
        self.remove_poleButton = QtWidgets.QPushButton(self.groupBox_9)
        self.remove_poleButton.setObjectName("remove_poleButton")
        self.gridLayout_19.addWidget(self.remove_poleButton, 1, 0, 1, 1)
        self.gridLayout_18.addWidget(self.groupBox_9, 0, 2, 5, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.stage_plot_comboBox = QtWidgets.QComboBox(self.groupBox_8)
        self.stage_plot_comboBox.setObjectName("stage_plot_comboBox")
        self.stage_plot_comboBox.addItem("")
        self.stage_plot_comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.stage_plot_comboBox)
        self.gridLayout_18.addLayout(self.horizontalLayout_7, 0, 0, 1, 2)
        self.stage_layout = QtWidgets.QVBoxLayout()
        self.stage_layout.setObjectName("stage_layout")
        self.gridLayout_18.addLayout(self.stage_layout, 1, 0, 6, 2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.gain_spinBox = QtWidgets.QDoubleSpinBox(self.groupBox_8)
        self.gain_spinBox.setMaximum(999999999990000.0)
        self.gain_spinBox.setProperty("value", 0.0)
        self.gain_spinBox.setObjectName("gain_spinBox")
        self.horizontalLayout_9.addWidget(self.gain_spinBox)
        self.gridLayout_18.addLayout(self.horizontalLayout_9, 5, 2, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_8, 3, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_15, 1, 0, 1, 2)
        self.delete_stageButton = QtWidgets.QPushButton(self.groupBox_7)
        self.delete_stageButton.setObjectName("delete_stageButton")
        self.gridLayout_17.addWidget(self.delete_stageButton, 2, 0, 1, 2)
        self.gridLayout_14.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_14, 3, 0, 2, 3)
        self.composition_layout = QtWidgets.QVBoxLayout()
        self.composition_layout.setObjectName("composition_layout")
        self.gridLayout_16.addLayout(self.composition_layout, 0, 2, 2, 1)
        self.gridLayout_5.addLayout(self.gridLayout_16, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1062, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionParameters = QtWidgets.QAction(MainWindow)
        self.actionParameters.setObjectName("actionParameters")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Filter Tool"))
        self.groupBox.setTitle(_translate("MainWindow", "Template"))
        self.label_5.setText(_translate("MainWindow", "Stop Band 1"))
        self.stopBand2_label.setText(_translate("MainWindow", "Stop Band 2"))
        self.label_2.setText(_translate("MainWindow", "Pass Band 1"))
        self.passBand2_label.setText(_translate("MainWindow", "Pass Band 2"))
        self.label.setText(_translate("MainWindow", "Min Attenuated"))
        self.label_3.setText(_translate("MainWindow", "Max Attenuated"))
        self.setTemplateButton.setText(_translate("MainWindow", "Set Template"))
        self.label_13.setText(_translate("MainWindow", "Type"))
        self.filterTypeComboBox.setItemText(0, _translate("MainWindow", "Low-pass"))
        self.filterTypeComboBox.setItemText(1, _translate("MainWindow", "High-pass"))
        self.filterTypeComboBox.setItemText(2, _translate("MainWindow", "Band-pass"))
        self.filterTypeComboBox.setItemText(3, _translate("MainWindow", "Band-reject"))
        self.filterTypeComboBox.setItemText(4, _translate("MainWindow", "All-pass"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Approximation Settings"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Parameters"))
        self.maxQRadioButton.setText(_translate("MainWindow", "Max Q Allowed"))
        self.minMaxRadioButton.setText(_translate("MainWindow", "Min Order"))
        self.label_14.setText(_translate("MainWindow", "Max Order"))
        self.customOrderRadioButton.setText(_translate("MainWindow", "Custom Order"))
        self.previewApproxButton.setText(_translate("MainWindow", "Preview Approximation"))
        self.clearApproxButton.setText(_translate("MainWindow", "Clear Approximations"))
        self.label_15.setText(_translate("MainWindow", "Approximation"))
        self.approximationComboBox.setItemText(0, _translate("MainWindow", "Butterworth"))
        self.approximationComboBox.setItemText(1, _translate("MainWindow", "Bessel"))
        self.approximationComboBox.setItemText(2, _translate("MainWindow", "Chebyshev Type I"))
        self.approximationComboBox.setItemText(3, _translate("MainWindow", "Chebyshev Type II"))
        self.approximationComboBox.setItemText(4, _translate("MainWindow", "Legendre"))
        self.approximationComboBox.setItemText(5, _translate("MainWindow", "Gauss"))
        self.approximationComboBox.setItemText(6, _translate("MainWindow", "Cauer elliptic"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Plots"))
        self.saveResultsPushButton.setToolTip(_translate("MainWindow", "Save results to .PDF report"))
        self.saveResultsPushButton.setText(_translate("MainWindow", "Save Results"))
        self.attenuationCurvesCheckBox.setText(_translate("MainWindow", "Attenuation Curves"))
        self.stepResponseCheckBox.setText(_translate("MainWindow", "Step Response"))
        self.phaseCheckBox.setText(_translate("MainWindow", "Phase"))
        self.sPlaneCheckBox.setText(_translate("MainWindow", "S Plane Diagram"))
        self.groupDelayCheckBox.setText(_translate("MainWindow", "Group Delay"))
        self.freqResponseCheckBox.setText(_translate("MainWindow", "Frequency Response"))
        self.computePushButton.setToolTip(_translate("MainWindow", "Compute approximation"))
        self.computePushButton.setText(_translate("MainWindow", "Compute"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.templates_tab), _translate("MainWindow", "Template"))
        self.label_6.setText(_translate("MainWindow", "Approximation"))
        self.current_approx_comboBox.setItemText(0, _translate("MainWindow", "None"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Zeros"))
        self.add_zeroButton.setText(_translate("MainWindow", "Add to Stage"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Poles"))
        self.add_poleButton.setText(_translate("MainWindow", "Add to Stage"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Stages"))
        self.label_8.setText(_translate("MainWindow", "Stage"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Zeros"))
        self.remove_zeroButton.setText(_translate("MainWindow", "Remove Zero"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Poles"))
        self.remove_poleButton.setText(_translate("MainWindow", "Remove Pole"))
        self.label_7.setText(_translate("MainWindow", "Stage Plot"))
        self.stage_plot_comboBox.setItemText(0, _translate("MainWindow", "Poles & Zeros"))
        self.stage_plot_comboBox.setItemText(1, _translate("MainWindow", "Transfer"))
        self.label_9.setText(_translate("MainWindow", "Gain"))
        self.delete_stageButton.setText(_translate("MainWindow", "Delete Stage"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Stages"))
        self.actionParameters.setText(_translate("MainWindow", "Parameters"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
